// this file was auto-generated by wrapit v1.3.3
#include "jlsimbody/common.h"

#include "jlSimTKcommon/Xml.h"

namespace jlcxx {
  template<> struct IsMirroredType<SimTK::Xml::Element> : std::false_type { };
  template<> struct DefaultConstructible<SimTK::Xml::Element> : std::false_type { };
  template<> struct SuperType<SimTK::Xml::Element> { typedef SimTK::Xml::Node type; };
}

namespace jlsimbody {

// Class generating the wrapper for type SimTK::Xml::Element
struct JlSimTK_Xml_Element: public Wrapper {

  JlSimTK_Xml_Element(jlcxx::Module& module): Wrapper(module){
    DEBUG_MSG("type SimTK::Xml::Element (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1042:32
    auto t = module.add_type<SimTK::Xml::Element>("XmlElement",
      jlcxx::julia_base_type<SimTK::Xml::Node>());
    CLEAR_DEBUG_MSG();

    type_ = std::unique_ptr<jlcxx::TypeWrapper<SimTK::Xml::Element>>(new jlcxx::TypeWrapper<SimTK::Xml::Element>(module, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>();

    DEBUG_MSG("void SimTK::Xml::Element::Element(const SimTK::String &, const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1069:10
    t.constructor<const SimTK::String &, const SimTK::String &>();
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Element SimTK::Xml::Element::clone() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1099:9
    t.method("clone", static_cast<SimTK::Xml::Element (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::clone));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::String & SimTK::Xml::Element::getElementTag() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1103:15
    t.method("getElementTag", static_cast<const SimTK::String & (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::getElementTag));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::setElementTag(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1105:6
    t.method("setElementTag", static_cast<void (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::setElementTag));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::insertNodeBefore(const SimTK::Xml::node_iterator &, SimTK::Xml::Node) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1112:6
    t.method("insertNodeBefore", static_cast<void (SimTK::Xml::Element::*)(const SimTK::Xml::node_iterator &, SimTK::Xml::Node) >(&SimTK::Xml::Element::insertNodeBefore));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::insertNodeAfter(const SimTK::Xml::node_iterator &, SimTK::Xml::Node) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1118:6
    t.method("insertNodeAfter", static_cast<void (SimTK::Xml::Element::*)(const SimTK::Xml::node_iterator &, SimTK::Xml::Node) >(&SimTK::Xml::Element::insertNodeAfter));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::appendNode(SimTK::Xml::Node) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1121:6
    t.method("appendNode", static_cast<void (SimTK::Xml::Element::*)(SimTK::Xml::Node) >(&SimTK::Xml::Element::appendNode));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::eraseNode(const SimTK::Xml::node_iterator &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1128:6
    t.method("eraseNode", static_cast<void (SimTK::Xml::Element::*)(const SimTK::Xml::node_iterator &) >(&SimTK::Xml::Element::eraseNode));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Node SimTK::Xml::Element::removeNode(const SimTK::Xml::node_iterator &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1134:6
    t.method("removeNode", static_cast<SimTK::Xml::Node (SimTK::Xml::Element::*)(const SimTK::Xml::node_iterator &) >(&SimTK::Xml::Element::removeNode));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Xml::Element::isValueElement() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1154:6
    t.method("isValueElement", static_cast<bool (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::isValueElement));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::String & SimTK::Xml::Element::getValue() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1163:15
    t.method("getValue", static_cast<const SimTK::String & (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::getValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::String & SimTK::Xml::Element::updValue() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1170:9
    t.method("updValue", static_cast<SimTK::String & (SimTK::Xml::Element::*)() >(&SimTK::Xml::Element::updValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::setValue(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1177:6
    t.method("setValue", static_cast<void (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::setValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::String & SimTK::Xml::Element::getRequiredElementValue(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1223:1
    t.method("getRequiredElementValue", static_cast<const SimTK::String & (SimTK::Xml::Element::*)(const SimTK::String &)  const>(&SimTK::Xml::Element::getRequiredElementValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::String SimTK::Xml::Element::getOptionalElementValue(const SimTK::String &, const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1230:1
    t.method("getOptionalElementValue", static_cast<SimTK::String (SimTK::Xml::Element::*)(const SimTK::String &, const SimTK::String &)  const>(&SimTK::Xml::Element::getOptionalElementValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Xml::Element::hasAttribute(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1272:6
    t.method("hasAttribute", static_cast<bool (SimTK::Xml::Element::*)(const SimTK::String &)  const>(&SimTK::Xml::Element::hasAttribute));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::setAttributeValue(const SimTK::String &, const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1276:6
    t.method("setAttributeValue", static_cast<void (SimTK::Xml::Element::*)(const SimTK::String &, const SimTK::String &) >(&SimTK::Xml::Element::setAttributeValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Xml::Element::eraseAttribute(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1282:6
    t.method("eraseAttribute", static_cast<void (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::eraseAttribute));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::String & SimTK::Xml::Element::getRequiredAttributeValue(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1287:1
    t.method("getRequiredAttributeValue", static_cast<const SimTK::String & (SimTK::Xml::Element::*)(const SimTK::String &)  const>(&SimTK::Xml::Element::getRequiredAttributeValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::String SimTK::Xml::Element::getOptionalAttributeValue(const SimTK::String &, const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1307:1
    t.method("getOptionalAttributeValue", static_cast<SimTK::String (SimTK::Xml::Element::*)(const SimTK::String &, const SimTK::String &)  const>(&SimTK::Xml::Element::getOptionalAttributeValue));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Attribute SimTK::Xml::Element::getRequiredAttribute(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1330:11
    t.method("getRequiredAttribute", static_cast<SimTK::Xml::Attribute (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::getRequiredAttribute));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Attribute SimTK::Xml::Element::getOptionalAttribute(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1335:11
    t.method("getOptionalAttribute", static_cast<SimTK::Xml::Attribute (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::getOptionalAttribute));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Array_<SimTK::Xml::Attribute> SimTK::Xml::Element::getAllAttributes() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1345:19
    t.method("getAllAttributes", static_cast<SimTK::Array_<SimTK::Xml::Attribute> (SimTK::Xml::Element::*)() >(&SimTK::Xml::Element::getAllAttributes));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::attribute_iterator SimTK::Xml::Element::attribute_begin() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1352:20
    t.method("attribute_begin", static_cast<SimTK::Xml::attribute_iterator (SimTK::Xml::Element::*)() >(&SimTK::Xml::Element::attribute_begin));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::attribute_iterator SimTK::Xml::Element::attribute_end() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1355:20
    t.method("attribute_end", static_cast<SimTK::Xml::attribute_iterator (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::attribute_end));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Xml::Element::hasElement(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1371:6
    t.method("hasElement", static_cast<bool (SimTK::Xml::Element::*)(const SimTK::String &)  const>(&SimTK::Xml::Element::hasElement));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Xml::Element::hasNode(SimTK::Xml::NodeType) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1374:6
    t.method("hasNode", static_cast<bool (SimTK::Xml::Element::*)(SimTK::Xml::NodeType)  const>(&SimTK::Xml::Element::hasNode));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Element SimTK::Xml::Element::getRequiredElement(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1380:9
    t.method("getRequiredElement", static_cast<SimTK::Xml::Element (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::getRequiredElement));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Element SimTK::Xml::Element::getOptionalElement(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1385:9
    t.method("getOptionalElement", static_cast<SimTK::Xml::Element (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::getOptionalElement));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Array_<SimTK::Xml::Element> SimTK::Xml::Element::getAllElements(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1394:17
    t.method("getAllElements", static_cast<SimTK::Array_<SimTK::Xml::Element> (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::getAllElements));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Array_<SimTK::Xml::Node> SimTK::Xml::Element::getAllNodes(SimTK::Xml::NodeType) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1403:14
    t.method("getAllNodes", static_cast<SimTK::Array_<SimTK::Xml::Node> (SimTK::Xml::Element::*)(SimTK::Xml::NodeType) >(&SimTK::Xml::Element::getAllNodes));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::element_iterator SimTK::Xml::Element::element_begin(const SimTK::String &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1410:18
    t.method("element_begin", static_cast<SimTK::Xml::element_iterator (SimTK::Xml::Element::*)(const SimTK::String &) >(&SimTK::Xml::Element::element_begin));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::element_iterator SimTK::Xml::Element::element_end() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1413:18
    t.method("element_end", static_cast<SimTK::Xml::element_iterator (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::element_end));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::node_iterator SimTK::Xml::Element::node_begin(SimTK::Xml::NodeType) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1419:15
    t.method("node_begin", static_cast<SimTK::Xml::node_iterator (SimTK::Xml::Element::*)(SimTK::Xml::NodeType) >(&SimTK::Xml::Element::node_begin));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::node_iterator SimTK::Xml::Element::node_end() (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1422:15
    t.method("node_end", static_cast<SimTK::Xml::node_iterator (SimTK::Xml::Element::*)()  const>(&SimTK::Xml::Element::node_end));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Xml::Element::isA(const SimTK::Xml::Node &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1430:13
    module_.method("Xml!Element!isA", static_cast<bool (*)(const SimTK::Xml::Node &) >(&SimTK::Xml::Element::isA));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Xml::Element & SimTK::Xml::Element::getAs(const SimTK::Xml::Node &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1433:23
    module_.method("Xml!Element!getAs", static_cast<const SimTK::Xml::Element & (*)(const SimTK::Xml::Node &) >(&SimTK::Xml::Element::getAs));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Xml::Element & SimTK::Xml::Element::getAs(SimTK::Xml::Node &) (" __HERE__ ")");
    // defined in simbody/SimTKcommon/internal/Xml.h:1436:17
    module_.method("Xml!Element!updAs", static_cast<SimTK::Xml::Element & (*)(SimTK::Xml::Node &) >(&SimTK::Xml::Element::getAs));
    CLEAR_DEBUG_MSG();
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<SimTK::Xml::Element>> type_;
};
std::shared_ptr<Wrapper> newJlSimTK_Xml_Element(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlSimTK_Xml_Element(module));
}

}
