module_name = "jlopensim"

input = [ 
    # # Actuators
    # "OpenSim/Actuators/CoordinateActuator.h",
    # "OpenSim/Actuators/ActivationCoordinateActuator.h",
    # "OpenSim/Actuators/PointActuator.h",
    # "OpenSim/Actuators/TorqueActuator.h",
    # "OpenSim/Actuators/BodyActuator.h",
    # "OpenSim/Actuators/PointToPointActuator.h",
    # "OpenSim/Actuators/ClutchedPathSpring.h",
    # "OpenSim/Actuators/SpringGeneralizedForce.h",
    # "OpenSim/Actuators/RigidTendonMuscle.h",
    # "OpenSim/Actuators/Millard2012AccelerationMuscle.h",
    # "OpenSim/Actuators/McKibbenActuator.h",
    # "OpenSim/Actuators/DeGrooteFregly2016Muscle.h",
    # "OpenSim/Actuators/ModelFactory.h",

    # # Analyses
    # "OpenSim/Analyses/Actuation.h",
    # "OpenSim/Analyses/Kinematics.h",
    # "OpenSim/Analyses/MuscleAnalysis.h",
    # "OpenSim/Analyses/InverseDynamics.h",
    # "OpenSim/Analyses/StaticOptimization.h",
    # "OpenSim/Analyses/ForceReporter.h",
    # "OpenSim/Analyses/PointKinematics.h",
    # "OpenSim/Analyses/BodyKinematics.h",
    # "OpenSim/Analyses/JointReaction.h",
    # "OpenSim/Analyses/StatesReporter.h",
    # "OpenSim/Analyses/InducedAccelerations.h",
    # "OpenSim/Analyses/ProbeReporter.h",
    # "OpenSim/Analyses/OutputReporter.h",
    # "OpenSim/Analyses/IMUDataReporter.h",
    # "OpenSim/Actuators/ModelOperators.h",
    # 
    # # Common
    # "OpenSim/Common/APDMDataReader.h",
    # "OpenSim/Common/APDMDataReaderSettings.h",
    # "OpenSim/Common/AbstractProperty.h",
    # "OpenSim/Common/Array.h",
    # "OpenSim/Common/ArrayPtrs.h",
    # "OpenSim/Common/C3DFileAdapter.h",
    # "OpenSim/Common/CSVFileAdapter.h",
    # "OpenSim/Common/CommonUtilities.h",
    # "OpenSim/Common/Component.h",
    # "OpenSim/Common/ComponentPath.h",
    # "OpenSim/Common/Constant.h",
    # "OpenSim/Common/DataAdapter.h",
    # "OpenSim/Common/DataTable.h",
    # "OpenSim/Common/DelimFileAdapter.h",
    # "OpenSim/Common/Event.h",
    # "OpenSim/Common/Exception.h",
    # "OpenSim/Common/ExperimentalSensor.h",
    # "OpenSim/Common/FileAdapter.h",
    # "OpenSim/Common/Function.h",
    # "OpenSim/Common/FunctionSet.h",
    # "OpenSim/Common/GCVSpline.h",
    # "OpenSim/Common/GCVSplineSet.h",
    # "OpenSim/Common/IMUDataReader.h",
    # "OpenSim/Common/IO.h",
    # "OpenSim/Common/LinearFunction.h",
    # "OpenSim/Common/LoadOpenSimLibrary.h",
    # "OpenSim/Common/LogSink.h",
    # "OpenSim/Common/Logger.h",
    # "OpenSim/Common/MarkerData.h",
    # "OpenSim/Common/ModelDisplayHints.h",
    # "OpenSim/Common/MultiplierFunction.h",
    # "OpenSim/Common/MultivariatePolynomialFunction.h",
    "OpenSim/Common/Object.h",
    # "OpenSim/Common/ObjectGroup.h",
    # "OpenSim/Common/PiecewiseConstantFunction.h",
    # "OpenSim/Common/PiecewiseLinearFunction.h",
    # "OpenSim/Common/PolynomialFunction.h",
    # "OpenSim/Common/Property.h",
    # "OpenSim/Common/PropertyGroup.h",
    # "OpenSim/Common/Reporter.h",
    # "OpenSim/Common/STOFileAdapter.h",
    # "OpenSim/Common/Scale.h",
    # "OpenSim/Common/ScaleSet.h",
    # "OpenSim/Common/Set.h",
    # "OpenSim/Common/SimmSpline.h",
    # "OpenSim/Common/Sine.h",
    # "OpenSim/Common/SmoothSegmentedFunction.h",
    # "OpenSim/Common/SmoothSegmentedFunctionFactory.h",
    # "OpenSim/Common/StateVector.h",
    # "OpenSim/Common/StepFunction.h",
    # "OpenSim/Common/Storage.h",
    # "OpenSim/Common/StorageInterface.h",
    # "OpenSim/Common/TRCFileAdapter.h",
    # "OpenSim/Common/TableSource.h",
    # "OpenSim/Common/TableUtilities.h",
    # "OpenSim/Common/TimeSeriesTable.h",
    # "OpenSim/Common/Units.h",
    # "OpenSim/Common/XYFunctionInterface.h",
    # "OpenSim/Common/XsensDataReader.h",

    # # MOCO
    # "OpenSim/Moco/About.h",
    # "OpenSim/Moco/MocoBounds.h",
    # "OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.h",
    # "OpenSim/Moco/MocoControlBoundConstraint.h",
    # "OpenSim/Moco/MocoFrameDistanceConstraint.h",
    # "OpenSim/Moco/MocoOutputConstraint.h",
    # "OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoContactImpulseTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoControlGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoControlTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoInitialActivationGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoInitialForceEquilibriumDGFGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoInitialVelocityEquilibriumDGFGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoJointReactionGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoMarkerFinalGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoMarkerTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoOrientationTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoAngularVelocityTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoOutputGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoPeriodicityGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoStateTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoSumSquaredStateGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoTranslationTrackingGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoStepTimeAsymmetryGoal.h",
    # "OpenSim/Moco/MocoGoal/MocoStepLengthAsymmetryGoal.h",
    # "OpenSim/Moco/MocoInverse.h",
    # "OpenSim/Moco/MocoParameter.h",
    # "OpenSim/Moco/MocoProblem.h",
    # "OpenSim/Moco/MocoStudy.h",
    # "OpenSim/Moco/MocoStudyFactory.h",
    # "OpenSim/Moco/MocoTrack.h",
    # "OpenSim/Moco/MocoTrajectory.h",
    # "OpenSim/Moco/MocoTropterSolver.h",
    # "OpenSim/Moco/MocoUtilities.h",
    # "OpenSim/Moco/MocoWeightSet.h",
    # "OpenSim/Moco/ModelOperatorsDGF.h",
    # "OpenSim/Moco/MocoScaleFactor.h",

    # # Simulation
    # "OpenSim/Simulation/Model/ModelComponent.h",
    # "OpenSim/Simulation/Model/ModelComponentSet.h",
    # "OpenSim/Simulation/Model/ComponentSet.h",

    # "OpenSim/Simulation/Solver.h",
    # "OpenSim/Simulation/InverseDynamicsSolver.h",
    # "OpenSim/Simulation/MomentArmSolver.h",

    # "OpenSim/Simulation/Model/Frame.h",
    # "OpenSim/Simulation/Model/PhysicalFrame.h",
    # "OpenSim/Simulation/Model/Ground.h",
    # "OpenSim/Simulation/Model/OffsetFrame.h",
    # "OpenSim/Simulation/Model/PhysicalOffsetFrame.h",

    # "OpenSim/Simulation/Model/Force.h",
    # "OpenSim/Simulation/Model/PrescribedForce.h",
    # "OpenSim/Simulation/Model/CoordinateLimitForce.h",
    # "OpenSim/Simulation/Model/ExternalForce.h",
    # "OpenSim/Simulation/Model/ContactGeometry.h",
    # "OpenSim/Simulation/Model/ContactHalfSpace.h",
    # "OpenSim/Simulation/Model/ContactMesh.h",
    # "OpenSim/Simulation/Model/ContactSphere.h",

    # "OpenSim/Simulation/Model/ElasticFoundationForce.h",
    # "OpenSim/Simulation/Model/HuntCrossleyForce.h",
    # "OpenSim/Simulation/Model/SmoothSphereHalfSpaceForce.h",

    # "OpenSim/Simulation/Model/ContactGeometrySet.h",
    # "OpenSim/Simulation/Model/Probe.h",
    # "OpenSim/Simulation/Model/ProbeSet.h",
    # "OpenSim/Simulation/Model/SystemEnergyProbe.h",
    # "OpenSim/Simulation/Model/JointInternalPowerProbe.h",
    # "OpenSim/Simulation/Model/ActuatorPowerProbe.h",
    # "OpenSim/Simulation/Model/ActuatorForceProbe.h",
    # "OpenSim/Simulation/Model/MuscleActiveFiberPowerProbe.h",
    # "OpenSim/Simulation/Model/Bhargava2004MuscleMetabolicsProbe.h",
    # "OpenSim/Simulation/Model/Bhargava2004SmoothedMuscleMetabolics.h",
    # "OpenSim/Simulation/Model/Umberger2010MuscleMetabolicsProbe.h",

    # "OpenSim/Simulation/Model/ModelVisualizer.h",
    # "OpenSim/Simulation/Model/Model.h",
    # "OpenSim/Simulation/Control/Control.h",
    # "OpenSim/Simulation/Control/ControlSet.h",
    # "OpenSim/Simulation/Control/ControlConstant.h",
    # "OpenSim/Simulation/Control/ControlLinearNode.h",
    # "OpenSim/Simulation/Control/ControlLinear.h",
    # "OpenSim/Simulation/Control/Controller.h",
    # "OpenSim/Simulation/Control/PrescribedController.h",
    # "OpenSim/Simulation/Manager/Manager.h",
    # "OpenSim/Simulation/Model/Analysis.h",
    # "OpenSim/Simulation/Model/AnalysisSet.h",
    # "OpenSim/Simulation/Model/ForceSet.h",
    # "OpenSim/Simulation/Model/ControllerSet.h",
    # "OpenSim/Simulation/Model/ExternalLoads.h",
    # "OpenSim/Simulation/Model/AbstractTool.h",
    # "OpenSim/Simulation/Model/Marker.h",
    # "OpenSim/Simulation/Model/MarkerSet.h",
    # "OpenSim/Simulation/SimbodyEngine/SimbodyEngine.h",

    # "OpenSim/Simulation/Wrap/WrapObject.h",
    # "OpenSim/Simulation/Wrap/PathWrapPoint.h",
    # "OpenSim/Simulation/Wrap/WrapSphere.h",
    # "OpenSim/Simulation/Wrap/WrapCylinder.h",
    # "OpenSim/Simulation/Wrap/WrapTorus.h",
    # "OpenSim/Simulation/Wrap/WrapEllipsoid.h",
    # "OpenSim/Simulation/Wrap/WrapObjectSet.h",
    # "OpenSim/Simulation/Wrap/PathWrap.h",
    # "OpenSim/Simulation/Wrap/PathWrapSet.h",
    # "OpenSim/Simulation/Wrap/WrapCylinderObst.h",
    # "OpenSim/Simulation/Wrap/WrapSphereObst.h",
    # "OpenSim/Simulation/Wrap/WrapDoubleCylinderObst.h",

    # "OpenSim/Simulation/SimbodyEngine/Body.h",
    # "OpenSim/Simulation/Model/BodySet.h",

    # "OpenSim/Simulation/Model/BodyScale.h",
    # "OpenSim/Simulation/Model/BodyScaleSet.h",

    # "OpenSim/Simulation/SimbodyEngine/Coordinate.h",
    # "OpenSim/Simulation/Model/CoordinateSet.h",

    # "OpenSim/Simulation/SimbodyEngine/TransformAxis.h",
    # "OpenSim/Simulation/SimbodyEngine/SpatialTransform.h",

    # "OpenSim/Simulation/SimbodyEngine/Joint.h",
    # "OpenSim/Simulation/SimbodyEngine/FreeJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/CustomJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/EllipsoidJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/BallJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/PinJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/SliderJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/WeldJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/GimbalJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/UniversalJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/PlanarJoint.h",
    # "OpenSim/Simulation/SimbodyEngine/ScapulothoracicJoint.h",
    # "OpenSim/Simulation/Model/JointSet.h",

    # "OpenSim/Simulation/Model/Marker.h",

    # "OpenSim/Simulation/Model/PathPoint.h",
    # "OpenSim/Simulation/Model/PathPointSet.h",
    # "OpenSim/Simulation/Model/ConditionalPathPoint.h",
    # "OpenSim/Simulation/Model/MovingPathPoint.h",
    # "OpenSim/Simulation/Model/PointForceDirection.h",
    # "OpenSim/Simulation/Model/GeometryPath.h",
    # "OpenSim/Simulation/Model/Ligament.h",
    # "OpenSim/Simulation/Model/Blankevoort1991Ligament.h",

    # "OpenSim/Simulation/SimbodyEngine/Constraint.h",
    # "OpenSim/Simulation/Model/ConstraintSet.h",
    # "OpenSim/Simulation/SimbodyEngine/WeldConstraint.h",
    # "OpenSim/Simulation/SimbodyEngine/PointConstraint.h",
    # "OpenSim/Simulation/SimbodyEngine/ConstantDistanceConstraint.h",
    # "OpenSim/Simulation/SimbodyEngine/CoordinateCouplerConstraint.h",
    # "OpenSim/Simulation/SimbodyEngine/PointOnLineConstraint.h",

    # "OpenSim/Simulation/Model/Actuator.h",
    # "OpenSim/Simulation/Model/PathActuator.h",
    # "OpenSim/Simulation/Model/Muscle.h",
    # "OpenSim/Simulation/Model/ActivationFiberLengthMuscle.h",
    # "OpenSim/Simulation/Model/ExpressionBasedPointToPointForce.h",
    # "OpenSim/Simulation/Model/ExpressionBasedCoordinateForce.h",
    # "OpenSim/Simulation/Model/PointToPointSpring.h",
    # "OpenSim/Simulation/Model/PathSpring.h",
    # "OpenSim/Simulation/Model/BushingForce.h",
    # "OpenSim/Simulation/Model/FunctionBasedBushingForce.h",
    # "OpenSim/Simulation/Model/ExpressionBasedBushingForce.h",

    # "OpenSim/Simulation/Solver.h",
    # "OpenSim/Simulation/AssemblySolver.h",
    # "OpenSim/Simulation/Reference.h",
    # "OpenSim/Simulation/MarkersReference.h",
    # "OpenSim/Simulation/CoordinateReference.h",
    # "OpenSim/Simulation/OrientationsReference.h",
    # "OpenSim/Simulation/InverseKinematicsSolver.h",
    # "OpenSim/Simulation/OpenSense/IMUPlacer.h",
    # "OpenSim/Simulation/OpenSense/IMU.h",
    # "OpenSim/Simulation/OpenSense/OpenSenseUtilities.h",

    # "OpenSim/Simulation/StatesTrajectory.h",
    # "OpenSim/Simulation/StatesTrajectoryReporter.h",

    # "OpenSim/Simulation/SimulationUtilities.h",
    # "OpenSim/Simulation/VisualizerUtilities.h",

    # "OpenSim/Simulation/TableProcessor.h",
    # "OpenSim/Simulation/PositionMotion.h",
    # "OpenSim/Actuators/osimActuatorsDLL.h",
    # "OpenSim/Actuators/MuscleFixedWidthPennationModel.h",
    # "OpenSim/Actuators/MuscleFirstOrderActivationDynamicModel.h",
    # "OpenSim/Actuators/Thelen2003Muscle.h",
    # "OpenSim/Actuators/Millard2012EquilibriumMuscle.h",
    # "OpenSim/Actuators/FiberCompressiveForceCosPennationCurve.h",
    # "OpenSim/Actuators/FiberCompressiveForceLengthCurve.h",
    # "OpenSim/Actuators/ActiveForceLengthCurve.h",
    # "OpenSim/Actuators/FiberForceLengthCurve.h",
    # "OpenSim/Actuators/ForceVelocityCurve.h",
    # "OpenSim/Actuators/ForceVelocityInverseCurve.h",
    # "OpenSim/Actuators/TendonForceLengthCurve.h",

    # # Tools
    # "OpenSim/Tools/ForwardTool.h",
    # "OpenSim/Tools/IKTask.h",
    # "OpenSim/Tools/IKMarkerTask.h",
    # "OpenSim/Tools/IKCoordinateTask.h",
    # "OpenSim/Tools/IKTaskSet.h",

    # "OpenSim/Tools/MarkerPair.h",
    # "OpenSim/Tools/MarkerPairSet.h",
    # "OpenSim/Tools/Measurement.h",
    # "OpenSim/Tools/MeasurementSet.h",

    # "OpenSim/Tools/GenericModelMaker.h",
    # "OpenSim/Tools/ModelScaler.h",
    # "OpenSim/Tools/MarkerPlacer.h",
    # "OpenSim/Tools/Tool.h",

    # "OpenSim/Tools/DynamicsTool.h",
    # "OpenSim/Tools/InverseDynamicsTool.h",

    # "OpenSim/Tools/TrackingTask.h",
    # "OpenSim/Tools/CMC_Task.h",
    # "OpenSim/Tools/CMC_Joint.h",
    # "OpenSim/Tools/CMC_Point.h",
    # "OpenSim/Tools/CMC_TaskSet.h",

    # "OpenSim/Tools/CMCTool.h",
    # "OpenSim/Tools/RRATool.h",
    # "OpenSim/Tools/ScaleTool.h",
    # "OpenSim/Tools/AnalyzeTool.h",
    # "OpenSim/Tools/InverseKinematicsTool.h",
    # "OpenSim/Tools/IMUInverseKinematicsTool.h",
]

include_dirs = [
    "/opt/opensim-core/",
    "/opt/opensim-core/Vendors/lepton/include",
    "/opt/opensim-core-fullrelease/sdk/include/simbody", 
    "/opt/opensim-core-fullrelease/sdk/include/tropter",
    "/opt/opensim-core/build/_deps/spdlog-src/include"
    ]

cxx-std="c++11"
