// this file was auto-generated by wrapit v0.1.0-61-g71d8603-dirty
#include "jlsimbody/common.h"

#include "jlSimTKcommon/Array.h"
#include "jlSimTKcommon/String.h"

namespace jlsimbody {

void define_SimTKcommon_String(jlcxx::Module& types, const ArrayWrapper& array_wrapper){

  DEBUG_MSG("Adding wrapper for type SimTK::String (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:62:7
  auto t2 = types.add_type<SimTK::String>("SimTK!String", jlcxx::julia_base_type<std::string>());
  t2.template constructor<>();

  /**********************************************************************/
  /* Wrappers for the methods of class SimTK::String
   */

  DEBUG_MSG("Adding wrapper for void SimTK::String::String(const char *) (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:71:1
  t2.constructor<const char *>();


  DEBUG_MSG("Adding wrapper for void SimTK::String::String(char) (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:74:10
  t2.constructor<char>();


  DEBUG_MSG("Adding wrapper for void SimTK::String::String(const std::string &) (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:77:1
  t2.constructor<const std::string &>();


  DEBUG_MSG("Adding wrapper for void SimTK::String::String(const SimTK::String &, int, int) (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:81:1
  t2.constructor<const SimTK::String &, int, int>();

  DEBUG_MSG("Adding setindex! method  to wrap char & SimTK::String::operator[](int) (" __HERE__ ")");
// defined in SimTKcommon/internal/String.h:88:7
  t2.method("cppsetindex!",
    [](SimTK::String& a, int i, char const & val){
    return a[i] = val;
  });

  DEBUG_MSG("Adding getindex method to wrap char & SimTK::String::operator[](int) (" __HERE__ ")");
  // defined in SimTKcommon/internal/String.h:88:7
  t2.method("cppgetindex",
    [](SimTK::String& a, int i){
    return a[i];
  });

  types.set_override_module(jl_base_module);
  DEBUG_MSG("Adding wrapper for int SimTK::String::length() (" __HERE__ ")");
  // signature to use in the veto list: int SimTK::String::length()
  // defined in SimTKcommon/internal/String.h:110:5
  t2.method("length", static_cast<int (SimTK::String::*)()  const>(&SimTK::String::length));
  types.unset_override_module();

  DEBUG_MSG("Adding wrapper for int SimTK::String::size() (" __HERE__ ")");
  // signature to use in the veto list: int SimTK::String::size()
  // defined in SimTKcommon/internal/String.h:106:5
  t2.method("size", static_cast<int (SimTK::String::*)()  const>(&SimTK::String::size));

  DEBUG_MSG("Adding wrapper for SimTK::String & SimTK::String::toUpper() (" __HERE__ ")");
  // signature to use in the veto list: SimTK::String & SimTK::String::toUpper()
  // defined in SimTKcommon/internal/String.h:276:34
  t2.method("toUpper", static_cast<SimTK::String & (SimTK::String::*)() >(&SimTK::String::toUpper));

  DEBUG_MSG("Adding wrapper for SimTK::String & SimTK::String::toLower() (" __HERE__ ")");
  // signature to use in the veto list: SimTK::String & SimTK::String::toLower()
  // defined in SimTKcommon/internal/String.h:279:34
  t2.method("toLower", static_cast<SimTK::String & (SimTK::String::*)() >(&SimTK::String::toLower));

  DEBUG_MSG("Adding wrapper for SimTK::String & SimTK::String::trimWhiteSpace() (" __HERE__ ")");
  // signature to use in the veto list: SimTK::String & SimTK::String::trimWhiteSpace()
  // defined in SimTKcommon/internal/String.h:283:34
  t2.method("trimWhiteSpace", static_cast<SimTK::String & (SimTK::String::*)() >(&SimTK::String::trimWhiteSpace));

  DEBUG_MSG("Adding wrapper for SimTK::String & SimTK::String::replaceAllChar(char, char) (" __HERE__ ")");
  // signature to use in the veto list: SimTK::String & SimTK::String::replaceAllChar(char, char)
  // defined in SimTKcommon/internal/String.h:286:34
  t2.method("replaceAllChar", static_cast<SimTK::String & (SimTK::String::*)(char, char) >(&SimTK::String::replaceAllChar));

  /* End of SimTK::String class method wrappers
   **********************************************************************/

  array_wrapper.template apply<SimTK::String>();

  DEBUG_MSG("End of wrapper definitions");

}
}
