// this file was auto-generated by wrapit v0.1.0-61-g71d8603-dirty
#include <type_traits>
#include "jlcxx/jlcxx.hpp"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

#include "jlSimTKcommon/Vec.h"

#ifdef VERBOSE_IMPORT
#  define DEBUG_MSG(a) std::cerr << a << "\n"
#  define CLEAR_DEBUG_MSG() std::cerr << "\33[2K\33[1F\33[0K\r"
#else
#  define DEBUG_MSG(a)
#  define CLEAR_DEBUG_MSG()
#endif
#define __HERE__  __FILE__ ":" QUOTE2(__LINE__)
#define QUOTE(arg) #arg
#define QUOTE2(arg) QUOTE(arg)

namespace jlsimbody {

void define_SimTKcommon_Vec(jlcxx::Module& types){

  // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:184:7
  auto t0 = types.add_type<jlcxx::Parametric<jlcxx::TypeVar<1>, jlcxx::TypeVar<2>, jlcxx::TypeVar<3>>>("SimTK!Vec");

  /**********************************************************************/
  /* Wrappers for the methods of class SimTK::Vec
   */
  auto t0_decl_methods = []<int M, typename ELT, int STRIDE> (jlcxx::TypeWrapper<SimTK::Vec<M, ELT, STRIDE>> wrapped){
    typedef SimTK::Vec<M, ELT, STRIDE> WrappedType;
    wrapped.template constructor<>(/*finalize=*/true);

    DEBUG_MSG("Adding wrapper for void SimTK::Vec::Vec<M, ELT, STRIDE>(int) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:485:14
    wrapped.template constructor<int>(/*finalize=*/true);
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for void SimTK::Vec::setToNaN() (" __HERE__ ")");
    // signature to use in the veto list: void SimTK::Vec::setToNaN()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:812:10
    wrapped.method("setToNaN", static_cast<void (WrappedType::*)() >(&WrappedType::setToNaN));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for void SimTK::Vec::setToZero() (" __HERE__ ")");
    // signature to use in the veto list: void SimTK::Vec::setToZero()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:817:10
    wrapped.method("setToZero", static_cast<void (WrappedType::*)() >(&WrappedType::setToZero));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for bool SimTK::Vec::isNaN() (" __HERE__ ")");
    // signature to use in the veto list: bool SimTK::Vec::isNaN()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:918:10
    wrapped.method("isNaN", static_cast<bool (WrappedType::*)()  const>(&WrappedType::isNaN));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for bool SimTK::Vec::isInf() (" __HERE__ ")");
    // signature to use in the veto list: bool SimTK::Vec::isInf()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:927:10
    wrapped.method("isInf", static_cast<bool (WrappedType::*)()  const>(&WrappedType::isInf));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for bool SimTK::Vec::isFinite() (" __HERE__ ")");
    // signature to use in the veto list: bool SimTK::Vec::isFinite()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:942:10
    wrapped.method("isFinite", static_cast<bool (WrappedType::*)()  const>(&WrappedType::isFinite));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("Adding wrapper for std::string SimTK::Vec::toString() (" __HERE__ ")");
    // signature to use in the veto list: std::string SimTK::Vec::toString()
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/SimTKcommon/internal/Vec.h:988:17
    wrapped.method("toString", static_cast<std::string (WrappedType::*)()  const>(&WrappedType::toString));
    CLEAR_DEBUG_MSG();
  };
  t0.apply<SimTK::Vec<1, double, 1>, SimTK::Vec<2, double, 1>, SimTK::Vec<3, double, 1>, SimTK::Vec<2, SimTK::Vec<3, double, 1>, 1>, SimTK::Vec<2, std::complex<double>, 1>, SimTK::Vec<3, std::complex<double>, 1>, SimTK::Vec<4, double, 1>, SimTK::Vec<4, SimTK::Vec<3, double, 1>, 1>, SimTK::Vec<4, SimTK::Row<3, double, 1>, 1>, SimTK::Vec<4, std::complex<double>, 1>, SimTK::Vec<5, double, 1>, SimTK::Vec<5, SimTK::Vec<3, double, 1>, 1>, SimTK::Vec<5, SimTK::Row<3, double, 1>, 1>, SimTK::Vec<6, double, 1>, SimTK::Vec<6, std::complex<double>, 1>, SimTK::Vec<7, double, 1>, SimTK::Vec<8, double, 1>, SimTK::Vec<9, double, 1>, SimTK::Vec<10, double, 1>, SimTK::Vec<10, std::complex<double>, 1>, SimTK::Vec<11, double, 1>, SimTK::Vec<12, double, 1>, SimTK::Vec<16, double, 1>>(t0_decl_methods);

  /* End of SimTK::Vec class method wrappers
   **********************************************************************/
  DEBUG_MSG("End of wrapper definitions");
  CLEAR_DEBUG_MSG();

}
}
