// this file was auto-generated by wrapit v1.3.3
#include "jlsimbody/common.h"

#include "jlSimTKcommon/Xml.h"

namespace jlsimbody {

class JlSimTK_Xml_Document;
class JlSimTK_Xml_Node;
class JlSimTK_Xml_Element;
class JlSimTK_Xml_node_iterator;
class JlSimTK_Xml_Attribute;
class JlSimTK_Xml_attribute_iterator;
class JlSimTK_Xml_element_iterator;
class JlSimTK_Xml_Text;
class JlSimTK_Xml_Comment;
class JlSimTK_Xml_Unknown;

std::shared_ptr<Wrapper> newJlSimTK_Xml_Document(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Node(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Element(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_node_iterator(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Attribute(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_attribute_iterator(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_element_iterator(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Text(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Comment(jlcxx::Module&);
std::shared_ptr<Wrapper> newJlSimTK_Xml_Unknown(jlcxx::Module&);

void define_SimTKcommon_Xml(jlcxx::Module& module, const ArrayWrapper& wraparray){

  std::vector<std::shared_ptr<Wrapper>> wrappers = {
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Document(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Node(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Element(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_node_iterator(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Attribute(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_attribute_iterator(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_element_iterator(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Text(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Comment(module)),
    std::shared_ptr<Wrapper>(newJlSimTK_Xml_Unknown(module))
  };

  DEBUG_MSG("Adding wrapper for enum SimTK::Xml::NodeType (" __HERE__ ")");
  // defined in /home/allen/.julia/artifacts/9c7f908e0daac4c2dbaa02c920e425b2543d790c/include/simbody/SimTKcommon/internal/Xml.h:72:6
  module.add_bits<SimTK::Xml::NodeType>("XmlNodeType", jlcxx::julia_type("CppEnum"));
  module.set_const("Xml_NoNode", SimTK::Xml::NoNode);
  module.set_const("Xml_ElementNode", SimTK::Xml::ElementNode);
  module.set_const("Xml_TextNode", SimTK::Xml::TextNode);
  module.set_const("Xml_CommentNode", SimTK::Xml::CommentNode);
  module.set_const("Xml_UnknownNode", SimTK::Xml::UnknownNode);
  module.set_const("Xml_NoJunkNodes", SimTK::Xml::NoJunkNodes);
  module.set_const("Xml_JunkNodes", SimTK::Xml::JunkNodes);
  module.set_const("Xml_AnyNodes", SimTK::Xml::AnyNodes);

  jlcxx::for_each_parameter_type<jlcxx::ParameterList<
    SimTK::Xml::Attribute,
    SimTK::Xml::Element,
    SimTK::Xml::Node
    >>(wraparray);

  for(const auto& w: wrappers) w->add_methods();

}

}
