// this file was auto-generated by wrapit v1.3.3
#include "jlsimbody/common.h"

#include "jlsimmath/Timestepper_and_Integrators.h"

namespace jlcxx {
  template<> struct IsMirroredType<SimTK::VerletIntegrator> : std::false_type { };
  template<> struct DefaultConstructible<SimTK::VerletIntegrator> : std::false_type { };
  template<> struct SuperType<SimTK::VerletIntegrator> { typedef SimTK::Integrator type; };
}

namespace jlsimbody {

// Class generating the wrapper for type SimTK::VerletIntegrator
struct JLSIMBODY_NO_EXPORT JlSimTK_VerletIntegrator : public Wrapper {

  JlSimTK_VerletIntegrator(jlcxx::Module& module): Wrapper(module){
    DEBUG_MSG("type SimTK::VerletIntegrator (" __HERE__ ")");
    // defined in simbody/simmath/VerletIntegrator.h:65:28
    jlcxx::TypeWrapper<SimTK::VerletIntegrator>  t = module.add_type<SimTK::VerletIntegrator>("VerletIntegrator",
      jlcxx::julia_base_type<SimTK::Integrator>());
    CLEAR_DEBUG_MSG();

    type_ = std::unique_ptr<jlcxx::TypeWrapper<SimTK::VerletIntegrator>>(new jlcxx::TypeWrapper<SimTK::VerletIntegrator>(module, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("void SimTK::VerletIntegrator::VerletIntegrator(const SimTK::System &) (" __HERE__ ")");
    // defined in simbody/simmath/VerletIntegrator.h:70:14
    t.constructor<const SimTK::System &>();
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::VerletIntegrator::VerletIntegrator(const SimTK::System &, SimTK::Real) (" __HERE__ ")");
    // defined in simbody/simmath/VerletIntegrator.h:74:5
    t.constructor<const SimTK::System &, SimTK::Real>();
    CLEAR_DEBUG_MSG();
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<SimTK::VerletIntegrator>> type_;
};
std::shared_ptr<Wrapper> newJlSimTK_VerletIntegrator(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlSimTK_VerletIntegrator(module));
}

}
