namespace = "jlosimCommon"
module_name = "osimCommon_Array"

veto_list = "Array_veto.h"
auto_veto = false

cxx-std="c++11"

export = "none"

propagation_mode = "methods"

input = [ 
    "SimTKcommon/internal/Array.h",
    "Array_instances.h",
]

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = [
    # "SimTKcommon/internal/CompositeNumericalTypes.h",
    # "SimTKcommon/internal/ResultType.h",
    # "SimTKcommon/Scalar.h",
    # "SimTKcommon/internal/NTraits.h",
    # "SimTKcommon/internal/BigMatrix.h",
    # "SimTKcommon/internal/MatrixHelper.h",
    # "SimTKcommon/internal/MatrixCharacteristics.h",
    # "SimTKcommon/internal/Vec.h",
    "SimTKcommon/internal/common.h",
    "SimTKcommon/internal/DecorativeGeometry.h",
    "SimTKcommon/internal/State.h",
    "SimTKcommon/internal/StateImpl.h",
    "SimTKcommon/internal/State.h",
    "SimTKcommon/internal/Event.h",
    "SimTKcommon/internal/Measure.h",
    "simbody/internal/MobilizedBody.h",
]

