#ifndef jlosimCommon_EXPORTS
    // extern template class SimTK::Array_<bool>;
    // extern template class SimTK::Array_<double>;
    // extern template class SimTK::Array_<int>;
    // extern template class SimTK::Array_<SimTK::String>;
    extern template class SimTK::Array_<SimTK::Vec<3, double, 1>>;
    extern template class SimTK::Array_<SimTK::Vec<6, double, 1>>;
    extern template class SimTK::Array_<SimTK::Vector_<double>>;
    // extern template class SimTK::Array_<SimTK::Array_<int>>;
    extern template class SimTK::Array_<ProbeMeasure<double>>;
    // extern template class SimTK::Array_<SimTK::CacheEntryIndex>;
    // extern template class SimTK::Array_<SimTK::CacheEntryInfo>;
    extern template class SimTK::Array_<OpenSim::AbstractProperty*>;
    extern template class SimTK::Array_<OpenSim::CoordinateReference>;
    extern template class SimTK::Array_<OpenSim::FreeJoint*>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ActiveForceLengthCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Appearance>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameterSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Bhargava2004SmoothedMuscleMetabolics_MuscleParameters>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::BodySet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Component>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ComponentSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Component>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ConstraintSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ContactGeometrySet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ControllerSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Coordinate>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ElasticFoundationForce::ContactParametersSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ExperimentalSensor>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ExternalLoads>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::FiberCompressiveForceCosPennationCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::FiberCompressiveForceLengthCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::FiberForceLengthCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ForceSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ForceVelocityCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::FrameGeometry>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Function>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::FunctionSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Geometry>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::GeometryPath>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Ground>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::HuntCrossleyForce::ContactParametersSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::IKTaskSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::JointSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MarkerSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MarkersReference>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoBounds>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoConstraintInfo>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoContactImpulseTrackingGoalGroup>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoContactTrackingGoalGroup>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoControlTrackingGoalReference>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoFinalBounds>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoFrameDistanceConstraintPair>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoGoal>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoInitialBounds>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoParameter>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoPathConstraint>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoPeriodicityGoalPair>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoPhase>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoProblem>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoScaleFactor>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoSolver>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoStepTimeAsymmetryGoalGroup>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoVariableInfo>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MocoWeightSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ModelDisplayHints>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Model>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ModelOperator>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ModelProcessor>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ModelVisualPreferences>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::MuscleFirstOrderActivationDynamicModel>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Object>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::OrientationWeightSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::PathPointSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::PathWrapSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::PhysicalFrame>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::PhysicalOffsetFrame>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::PiecewiseLinearFunction>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::ProbeSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Set<OpenSim::MarkerWeight, OpenSim::Object> >;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Set<OpenSim::OrientationWeight, OpenSim::Object> >;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::SpatialTransform>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::SurfaceProperties>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::TableOperator>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::TableProcessor>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::TendonForceLengthCurve>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::TransformAxis>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameterSet>>;
    extern template class SimTK::Array_<SimTK::ClonePtr<OpenSim::WrapObjectSet>>;
    extern template class SimTK::Array_<SimTK::ReferencePtr<OpenSim::Body>>;
    extern template class SimTK::Array_<SimTK::ReferencePtr<OpenSim::Component::StateVariable const>>;
    extern template class SimTK::Array_<SimTK::ReferencePtr<OpenSim::Component>>;
    extern template class SimTK::Array_<SimTK::ConstraintErrInfo>;
    extern template class SimTK::Array_<SimTK::ContinuousVarInfo>;
    // extern template class SimTK::Array_<SimTK::DecorativeGeometry>;
    // extern template class SimTK::Array_<SimTK::DiscreteVarInfo>;
    // extern template class SimTK::Array_<SimTK::EventId>;
    // extern template class SimTK::Array_<SimTK::EventTriggerInfo>;
    extern template class SimTK::Array_<SimTK::Function_<double> const*>;
    extern template class SimTK::Array_<SimTK::Markers::MarkerIx>;
    extern template class SimTK::Array_<SimTK::Markers::Marker, SimTK::Markers::MarkerIx>;
    // extern template class SimTK::Array_<SimTK::Measure_<double>>;
    extern template class SimTK::Array_<SimTK::MobilizedBodyIndex>;
    extern template class SimTK::Array_<SimTK::MobilizerQIndex>;
    extern template class SimTK::Array_<SimTK::OrientationSensors::OSensorIx>;
    extern template class SimTK::Array_<SimTK::OrientationSensors::OSensor, SimTK::OrientationSensors::OSensorIx>;
    // extern template class SimTK::Array_<SimTK::Rotation_<double>>;
    extern template class SimTK::Array_<SimTK::Spline_<double>>;
    // extern template class SimTK::Array_<SimTK::SystemQIndex>;
    // extern template class SimTK::Array_<SimTK::SystemUIndex>;
    extern template class SimTK::Array_<SimTK::Vec<3, double, 1>, SimTK::Markers::ObservationIx>;
    extern template class SimTK::Array_<SimTK::Xml::Element>;
#endif
