namespace = "jlosimCommon"
module_name = "osimCommon_CoordinateAxis"

auto_veto = true

cxx-std="c++11"

export = "none"

input = [ 
    "SimTKcommon/internal/CoordinateAxis.h",
]

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

