namespace = "jlosimCommon"
module_name = "osimCommon_Events"

veto_list = "Events_veto.h"
auto_veto = false

cxx-std="c++11"

export = "none"

input = [
    # "SimTKcommon/internal/Event.h",
    "SimTKcommon/internal/EventHandler.h",
    "SimTKcommon/internal/EventReporter.h",
    "SimTKcommon/internal/EventReporter.h",
]

propagation_mode = "types"

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = []

