namespace = "jlosimCommon"
module_name = "osimCommon_Mat"

veto_list = "Mat_veto.h"
auto_veto = true

cxx-std="c++11"

export = "none"

input = [
    "SimTKcommon/internal/Mat.h",
    "Mat_instances.h",
]

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = [
    "SimTKcommon/internal/CompositeNumericalTypes.h",
    "SimTKcommon/internal/ResultType.h",
    "SimTKcommon/Scalar.h",
    "SimTKcommon/internal/negator.h",
    "SimTKcommon/internal/conjugate.h",
    "SimTKcommon/internal/NTraits.h",
    "SimTKcommon/internal/Row.h",
    "SimTKcommon/internal/Vec.h",
]
