namespace = "jlsimbody"
module_name = "simbody_SimbodyMatterSubsystem"

veto_list = "SimbodyMatterSubsystem_veto.h"
auto_veto = true

cxx-std="c++11"

export = "none"

input = [
    "simbody/internal/SimbodyMatterSubsystem.h",
]

propagation_mode = "types"

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = []

