namespace = "jlosimCommon"
module_name = "osimCommon_SystemSubsystem"

veto_list = "System-Subsystem_veto.h"
auto_veto = false

cxx-std="c++11"

export = "none"

input = [
    "SimTKcommon/internal/System.h",
    "SimTKcommon/internal/Subsystem.h",
]

propagation_mode = "methods"

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = [
    "SimTKcommon/internal/EventHandler.h",
    "SimTKcommon/internal/EventReporter.h",
    "SimTKcommon/internal/Measure.h",
]

