namespace = "jlosimCommon"
module_name = "osimCommon_Vec"

veto_list = "Vec_veto.h"
auto_veto = true

cxx-std="c++11"

export = "none"

input = [ 
    "SimTKcommon/internal/Vec.h",
    "SimTKcommon/internal/UnitVec.h",
    "SimTKcommon/internal/Quaternion.h",
    "Vec_instances.h",
]

include_dirs = [
    ".",
    "/opt/opensim-core-fullrelease/sdk/include/simbody"
    ]

extra_headers = [
    "SimTKcommon/internal/CompositeNumericalTypes.h",
    "SimTKcommon/internal/ResultType.h",
    "SimTKcommon/Scalar.h",
    "SimTKcommon/internal/negator.h",
    "SimTKcommon/internal/conjugate.h",
    "SimTKcommon/internal/NTraits.h",
    # "SimTKcommon/internal/common.h",
    # "SimTKcommon/internal/Row.h",
    # "Row_instances.h",
]

