// this file was auto-generated by wrapit v1.3.3
#include "jlsimbody/common.h"

#include "jlsimbody/Constraints.h"

namespace jlcxx {
  template<> struct IsMirroredType<SimTK::Constraint::NoSlip1D> : std::false_type { };
  template<> struct DefaultConstructible<SimTK::Constraint::NoSlip1D> : std::false_type { };
	template<> struct SuperType<SimTK::Constraint::NoSlip1D> { typedef SimTK::Constraint type; };
}

namespace jlsimbody {

// Class generating the wrapper for type SimTK::Constraint::NoSlip1D
struct JlSimTK_Constraint_NoSlip1D: public Wrapper {

  JlSimTK_Constraint_NoSlip1D(jlcxx::Module& module): Wrapper(module){
    DEBUG_MSG("type SimTK::Constraint::NoSlip1D (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:728:40
    auto t = module.add_type<SimTK::Constraint::NoSlip1D>(
      "NoSlip1DConstraint",
      jlcxx::julia_base_type<SimTK::Constraint>());
    CLEAR_DEBUG_MSG();

    type_ = std::unique_ptr<jlcxx::TypeWrapper<SimTK::Constraint::NoSlip1D>>(new jlcxx::TypeWrapper<SimTK::Constraint::NoSlip1D>(module, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>();

    DEBUG_MSG("void SimTK::Constraint::NoSlip1D::NoSlip1D(SimTK::MobilizedBody &, const SimTK::Vec3 &, const SimTK::UnitVec3 &, SimTK::MobilizedBody &, SimTK::MobilizedBody &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:738:5
    t.constructor<SimTK::MobilizedBody &, const SimTK::Vec3 &, const SimTK::UnitVec3 &, SimTK::MobilizedBody &, SimTK::MobilizedBody &>();
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Constraint::NoSlip1D::setContactPoint(SimTK::State &, const SimTK::Vec3 &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:748:10
    t.method("setContactPoint", static_cast<void (SimTK::Constraint::NoSlip1D::*)(SimTK::State &, const SimTK::Vec3 &)  const>(&SimTK::Constraint::NoSlip1D::setContactPoint));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("void SimTK::Constraint::NoSlip1D::setDirection(SimTK::State &, const SimTK::UnitVec3 &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:753:10
    t.method("setDirection", static_cast<void (SimTK::Constraint::NoSlip1D::*)(SimTK::State &, const SimTK::UnitVec3 &)  const>(&SimTK::Constraint::NoSlip1D::setDirection));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Vec3 & SimTK::Constraint::NoSlip1D::getContactPoint(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:757:17
    t.method("getContactPoint", static_cast<const SimTK::Vec3 & (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getContactPoint));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::UnitVec3 & SimTK::Constraint::NoSlip1D::getDirection(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:760:21
    t.method("getDirection", static_cast<const SimTK::UnitVec3 & (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getDirection));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::setDirectionDisplayLength(SimTK::Real) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:768:15
    t.method("setDirectionDisplayLength", static_cast<SimTK::Constraint::NoSlip1D & (SimTK::Constraint::NoSlip1D::*)(SimTK::Real) >(&SimTK::Constraint::NoSlip1D::setDirectionDisplayLength));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::setPointDisplayRadius(SimTK::Real) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:771:15
    t.method("setPointDisplayRadius", static_cast<SimTK::Constraint::NoSlip1D & (SimTK::Constraint::NoSlip1D::*)(SimTK::Real) >(&SimTK::Constraint::NoSlip1D::setPointDisplayRadius));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getDirectionDisplayLength() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:774:10
    t.method("getDirectionDisplayLength", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getDirectionDisplayLength));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getPointDisplayRadius() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:777:10
    t.method("getPointDisplayRadius", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getPointDisplayRadius));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::setDefaultContactPoint(const SimTK::Vec3 &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:783:15
    t.method("setDefaultContactPoint", static_cast<SimTK::Constraint::NoSlip1D & (SimTK::Constraint::NoSlip1D::*)(const SimTK::Vec3 &) >(&SimTK::Constraint::NoSlip1D::setDefaultContactPoint));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::setDefaultDirection(const SimTK::UnitVec3 &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:786:15
    t.method("setDefaultDirection", static_cast<SimTK::Constraint::NoSlip1D & (SimTK::Constraint::NoSlip1D::*)(const SimTK::UnitVec3 &) >(&SimTK::Constraint::NoSlip1D::setDefaultDirection));
    CLEAR_DEBUG_MSG();

    #ifdef JLSIMBODY_USE_SIMTK_UNIQUEINDEX_TYPES
    DEBUG_MSG("SimTK::MobilizedBodyIndex SimTK::Constraint::NoSlip1D::getCaseMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:793:24
    t.method("getCaseMobilizedBodyIndex", static_cast<SimTK::MobilizedBodyIndex (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getCaseMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #else
    DEBUG_MSG("int SimTK::Constraint::NoSlip1D::getCaseMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:793:24
    t.method("getCaseMobilizedBodyIndex", reinterpret_cast<int (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getCaseMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #endif

    #ifdef JLSIMBODY_USE_SIMTK_UNIQUEINDEX_TYPES
    DEBUG_MSG("SimTK::MobilizedBodyIndex SimTK::Constraint::NoSlip1D::getMovingBodyMobilizedBodyIndex(int) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:796:24
    t.method("getMovingBodyMobilizedBodyIndex", static_cast<SimTK::MobilizedBodyIndex (SimTK::Constraint::NoSlip1D::*)(int)  const>(&SimTK::Constraint::NoSlip1D::getMovingBodyMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #else
    DEBUG_MSG("int SimTK::Constraint::NoSlip1D::getMovingBodyMobilizedBodyIndex(int) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:796:24
    t.method("getMovingBodyMobilizedBodyIndex", reinterpret_cast<int (SimTK::Constraint::NoSlip1D::*)(int)  const>(&SimTK::Constraint::NoSlip1D::getMovingBodyMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #endif

    DEBUG_MSG("const SimTK::UnitVec3 & SimTK::Constraint::NoSlip1D::getDefaultDirection() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:800:21
    t.method("getDefaultDirection", static_cast<const SimTK::UnitVec3 & (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getDefaultDirection));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Vec3 & SimTK::Constraint::NoSlip1D::getDefaultContactPoint() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:803:21
    t.method("getDefaultContactPoint", static_cast<const SimTK::Vec3 & (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::getDefaultContactPoint));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getVelocityError(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:812:10
    t.method("getVelocityError", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getVelocityError));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getAccelerationError(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:820:10
    t.method("getAccelerationError", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getAccelerationError));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getMultiplier(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:828:10
    t.method("getMultiplier", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getMultiplier));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Real SimTK::Constraint::NoSlip1D::getForceAtContactPoint(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:833:10
    t.method("getForceAtContactPoint", static_cast<SimTK::Real (SimTK::Constraint::NoSlip1D::*)(const SimTK::State &)  const>(&SimTK::Constraint::NoSlip1D::getForceAtContactPoint));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Constraint & SimTK::Constraint::NoSlip1D::upcast() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:836:5
    t.method("upcast", static_cast<const SimTK::Constraint & (SimTK::Constraint::NoSlip1D::*)()  const>(&SimTK::Constraint::NoSlip1D::upcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint & SimTK::Constraint::NoSlip1D::updUpcast() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:836:5
    t.method("updUpcast", static_cast<SimTK::Constraint & (SimTK::Constraint::NoSlip1D::*)() >(&SimTK::Constraint::NoSlip1D::updUpcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Constraint::NoSlip1D::isInstanceOf(const SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:836:5
    module_.method("Constraint!NoSlip1D!isInstanceOf", static_cast<bool (*)(const SimTK::Constraint &) >(&SimTK::Constraint::NoSlip1D::isInstanceOf));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::downcast(const SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:836:5
    module_.method("Constraint!NoSlip1D!downcast", static_cast<const SimTK::Constraint::NoSlip1D & (*)(const SimTK::Constraint &) >(&SimTK::Constraint::NoSlip1D::downcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::NoSlip1D & SimTK::Constraint::NoSlip1D::updDowncast(SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:836:5
    module_.method("Constraint!NoSlip1D!updDowncast", static_cast<SimTK::Constraint::NoSlip1D & (*)(SimTK::Constraint &) >(&SimTK::Constraint::NoSlip1D::updDowncast));
    CLEAR_DEBUG_MSG();
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<SimTK::Constraint::NoSlip1D>> type_;
};
std::shared_ptr<Wrapper> newJlSimTK_Constraint_NoSlip1D(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlSimTK_Constraint_NoSlip1D(module));
}

}
