// this file was auto-generated by wrapit v1.3.3
#include "jlsimbody/common.h"

#include "jlsimbody/Constraints.h"

namespace jlcxx {
  template<> struct IsMirroredType<SimTK::Constraint::ConstantOrientation> : std::false_type { };
  template<> struct DefaultConstructible<SimTK::Constraint::ConstantOrientation> : std::false_type { };
	template<> struct SuperType<SimTK::Constraint::ConstantOrientation> { typedef SimTK::Constraint type; };
}

namespace jlsimbody {

// Class generating the wrapper for type SimTK::Constraint::ConstantOrientation
struct JlSimTK_Constraint_ConstantOrientation: public Wrapper {

  JlSimTK_Constraint_ConstantOrientation(jlcxx::Module& module): Wrapper(module){
    DEBUG_MSG("type SimTK::Constraint::ConstantOrientation (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:671:40
    auto t = module.add_type<SimTK::Constraint::ConstantOrientation>(
      "ConstantOrientationConstraint",
      jlcxx::julia_base_type<SimTK::Constraint>());
    CLEAR_DEBUG_MSG();

    type_ = std::unique_ptr<jlcxx::TypeWrapper<SimTK::Constraint::ConstantOrientation>>(new jlcxx::TypeWrapper<SimTK::Constraint::ConstantOrientation>(module, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>();

    DEBUG_MSG("void SimTK::Constraint::ConstantOrientation::ConstantOrientation(SimTK::MobilizedBody &, const SimTK::Rotation &, SimTK::MobilizedBody &, const SimTK::Rotation &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:675:5
    t.constructor<SimTK::MobilizedBody &, const SimTK::Rotation &, SimTK::MobilizedBody &, const SimTK::Rotation &>();
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::ConstantOrientation & SimTK::Constraint::ConstantOrientation::setDefaultBaseRotation(const SimTK::Rotation &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:684:26
    t.method("setDefaultBaseRotation", static_cast<SimTK::Constraint::ConstantOrientation & (SimTK::Constraint::ConstantOrientation::*)(const SimTK::Rotation &) >(&SimTK::Constraint::ConstantOrientation::setDefaultBaseRotation));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::ConstantOrientation & SimTK::Constraint::ConstantOrientation::setDefaultFollowerRotation(const SimTK::Rotation &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:685:26
    t.method("setDefaultFollowerRotation", static_cast<SimTK::Constraint::ConstantOrientation & (SimTK::Constraint::ConstantOrientation::*)(const SimTK::Rotation &) >(&SimTK::Constraint::ConstantOrientation::setDefaultFollowerRotation));
    CLEAR_DEBUG_MSG();

    #ifdef JLSIMBODY_USE_SIMTK_UNIQUEINDEX_TYPES
    DEBUG_MSG("SimTK::MobilizedBodyIndex SimTK::Constraint::ConstantOrientation::getBaseMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:688:24
    t.method("getBaseMobilizedBodyIndex", static_cast<SimTK::MobilizedBodyIndex (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getBaseMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #else
    DEBUG_MSG("int SimTK::Constraint::ConstantOrientation::getBaseMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:688:24
    t.method("getBaseMobilizedBodyIndex", reinterpret_cast<int (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getBaseMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #endif

    #ifdef JLSIMBODY_USE_SIMTK_UNIQUEINDEX_TYPES
    DEBUG_MSG("SimTK::MobilizedBodyIndex SimTK::Constraint::ConstantOrientation::getFollowerMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:689:24
    t.method("getFollowerMobilizedBodyIndex", static_cast<SimTK::MobilizedBodyIndex (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getFollowerMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #else
    DEBUG_MSG("int SimTK::Constraint::ConstantOrientation::getFollowerMobilizedBodyIndex() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:689:24
    t.method("getFollowerMobilizedBodyIndex", reinterpret_cast<int (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getFollowerMobilizedBodyIndex));
    CLEAR_DEBUG_MSG();
    #endif

    DEBUG_MSG("const SimTK::Rotation & SimTK::Constraint::ConstantOrientation::getDefaultBaseRotation() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:691:21
    t.method("getDefaultBaseRotation", static_cast<const SimTK::Rotation & (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getDefaultBaseRotation));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Rotation & SimTK::Constraint::ConstantOrientation::getDefaultFollowerRotation() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:692:21
    t.method("getDefaultFollowerRotation", static_cast<const SimTK::Rotation & (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::getDefaultFollowerRotation));
    CLEAR_DEBUG_MSG();

    // DEBUG_MSG("const SimTK::Rotation & SimTK::Constraint::ConstantOrientation::getBaseRotation(const SimTK::State &) (" __HERE__ ")");
    // // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:695:21
    // t.method("getBaseRotation", static_cast<const SimTK::Rotation & (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getBaseRotation));
    // CLEAR_DEBUG_MSG();

    // DEBUG_MSG("const SimTK::Rotation & SimTK::Constraint::ConstantOrientation::getFollowerRotation(const SimTK::State &) (" __HERE__ ")");
    // // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:696:21
    // t.method("getFollowerRotation", static_cast<const SimTK::Rotation & (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getFollowerRotation));
    // CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Vec3 SimTK::Constraint::ConstantOrientation::getPositionErrors(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:699:10
    t.method("getPositionErrors", static_cast<SimTK::Vec3 (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getPositionErrors));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Vec3 SimTK::Constraint::ConstantOrientation::getVelocityErrors(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:700:10
    t.method("getVelocityErrors", static_cast<SimTK::Vec3 (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getVelocityErrors));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Vec3 SimTK::Constraint::ConstantOrientation::getAccelerationErrors(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:703:10
    t.method("getAccelerationErrors", static_cast<SimTK::Vec3 (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getAccelerationErrors));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Vec3 SimTK::Constraint::ConstantOrientation::getMultipliers(const SimTK::State &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:704:10
    t.method("getMultipliers", static_cast<SimTK::Vec3 (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getMultipliers));
    CLEAR_DEBUG_MSG();

    // DEBUG_MSG("SimTK::Vec3 SimTK::Constraint::ConstantOrientation::getTorqueOnFollowerBody(const SimTK::State &) (" __HERE__ ")");
    // // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:705:10
    // t.method("getTorqueOnFollowerBody", static_cast<SimTK::Vec3 (SimTK::Constraint::ConstantOrientation::*)(const SimTK::State &)  const>(&SimTK::Constraint::ConstantOrientation::getTorqueOnFollowerBody));
    // CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Constraint & SimTK::Constraint::ConstantOrientation::upcast() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:708:5
    t.method("upcast", static_cast<const SimTK::Constraint & (SimTK::Constraint::ConstantOrientation::*)()  const>(&SimTK::Constraint::ConstantOrientation::upcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint & SimTK::Constraint::ConstantOrientation::updUpcast() (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:708:5
    t.method("updUpcast", static_cast<SimTK::Constraint & (SimTK::Constraint::ConstantOrientation::*)() >(&SimTK::Constraint::ConstantOrientation::updUpcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("bool SimTK::Constraint::ConstantOrientation::isInstanceOf(const SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:708:5
    module_.method("Constraint!ConstantOrientation!isInstanceOf", static_cast<bool (*)(const SimTK::Constraint &) >(&SimTK::Constraint::ConstantOrientation::isInstanceOf));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("const SimTK::Constraint::ConstantOrientation & SimTK::Constraint::ConstantOrientation::downcast(const SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:708:5
    module_.method("Constraint!ConstantOrientation!downcast", static_cast<const SimTK::Constraint::ConstantOrientation & (*)(const SimTK::Constraint &) >(&SimTK::Constraint::ConstantOrientation::downcast));
    CLEAR_DEBUG_MSG();

    DEBUG_MSG("SimTK::Constraint::ConstantOrientation & SimTK::Constraint::ConstantOrientation::updDowncast(SimTK::Constraint &) (" __HERE__ ")");
    // defined in /opt/opensim-core-fullrelease/sdk/include/simbody/simbody/internal/Constraint.h:708:5
    module_.method("Constraint!ConstantOrientation!updDowncast", static_cast<SimTK::Constraint::ConstantOrientation & (*)(SimTK::Constraint &) >(&SimTK::Constraint::ConstantOrientation::updDowncast));
    CLEAR_DEBUG_MSG();
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<SimTK::Constraint::ConstantOrientation>> type_;
};
std::shared_ptr<Wrapper> newJlSimTK_Constraint_ConstantOrientation(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlSimTK_Constraint_ConstantOrientation(module));
}

}
